### ISSUE TITLE
MVP for demo

### ISSUE THREAD

**Issue by secretshardul** [skiran017/near-swap#28]
#### We need to
1. Consolidate the repositories. Currently there are 3 repos.
2. Fix debouncing
3. Update the SDK config to allow installs from github. Currently we're using local folder installs.
4. Migrate to the new wallet selector.
5. Display token balances. This code should do. It needs the provider object-

```ts
const res = await provider.query<CodeResult>({
  request_type: 'call_function',
  account_id: tokenId,
  method_name: 'ft_balance_of',
  args_base64: Buffer.from(JSON.stringify({ account_id: accountId })).toString('base64'),
  finality: 'optimistic'
})
```

**Comment by skiran017** [comment]
1. lets finalize arbitoor/arbitoor-ui, that is updated with the latest code
2. fixed debouncing, initiates search after 1s.
3. updated the sdk to allow install from github
4. Migrated to latest wallet-selector v4.0.0

**Comment by skiran017** [comment]
5. Display token balances is done and deployed the changes 
https://github.com/arbitoor/arbitoor-ui
